# Note: conda dependencies have only 1 "="
#       pip dependencies have 2 "=="
# Fuse pip dependencies together under one " - pip" item
#       Otherwise, only some of the are installed, because conda creates a temporary requirements.txt file
#       only the last -pip section

name: gghead

channels:
  - pytorch
  - conda-forge
  #- nvidia/label/cuda-11.8.0
  #- nvidia/label/cuda-12.4.0

dependencies:
  #- python=3.8
  - pip
  - jupyter

  # CUDA and PyTorch
  #- gcc<12  # Needs to be <12 because nvcc does not like gcc>11
  - pytorch
  - torchvision
  - pytorch-cuda
  - cuda-nvcc  # for nvcc
  - cuda-cudart-dev  # for cuda_runtime.h
  - cuda-toolkit
  - libcusparse-dev
  - glm  # For gsplat

  # claforte: If you encounter problems building the entire micromamba environment at once,
  # comment out the pip packages and add them incrementally after creating the initial env.
  - pip:
      - ninja
      - imageio
      - imageio-ffmpeg
      - tyro
      - environs

      - elias>=0.3.4
      - dreifus
      - mediapy # claforte: seems outdated
      - wandb
      - pytorch_lightning

      # For EG3D visualizer
      - eg3d@git+https://github.com/tobias-kirschstein/eg3d.git
      - imgui #>=1.3.0
      - glfw #>=2.2.0
      - pyopengl #>=3.1.5

      # Data processing
      - visage >= 0.2.2